[mcp_servers.pencil]
command = "C:\\Users\\Thaw Linn Htet\\AppData\\Local\\Programs\\Pencil\\resources\\app.asar.unpacked\\out\\mcp-server-windows-x64.exe"
args = [ "--app", "desktop", "--agent", "codexCLI" ]
