/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/workspaces/{workspaceId}/reasoning/review-brief": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Create or update a Review Brief */
        put: operations["saveReviewBrief"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/architecture-document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an owned Architecture Document */
        get: operations["get"];
        /** Save an Architecture Document with optimistic concurrency */
        put: operations["save"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/ai-consent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current AI Processing Consent and bounded context policy */
        get: operations["get_1"];
        /** Grant AI Processing Consent for the presented policy version */
        put: operations["grant"];
        post?: never;
        /** Withdraw AI Processing Consent */
        delete: operations["withdraw"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List owned Workspaces */
        get: operations["list"];
        put?: never;
        /** Create a custom Workspace */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore an owned Workspace */
        post: operations["restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/reasoning/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a Requirement */
        post: operations["createRequirement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/reasoning/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an Unresolved Question */
        post: operations["createQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/reasoning/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a Decision */
        post: operations["createDecision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/reasoning/assumptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an Assumption */
        post: operations["createAssumption"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive an owned Workspace */
        post: operations["archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/architecture-revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an immutable Architecture Revision */
        post: operations["createRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/custom-design": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a blank Custom Design Workspace */
        post: operations["createCustomDesign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/stripe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive a signed Stripe webhook */
        post: operations["stripeWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import-packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an Architecture Review Workspace from a validated Import Package */
        post: operations["importPackage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import-packages/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a portable Import Package without creating a Workspace */
        post: operations["validateImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/challenges/{slug}/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start an independent private Workspace from a published Challenge Version */
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a Stripe Customer Portal session */
        post: operations["customerPortal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a Stripe Checkout session */
        post: operations["checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/checkout/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconcile a completed Stripe Checkout session for the signed-in user */
        post: operations["completeCheckout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/architecture-review-workspaces/manual-recreation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a Manual Recreation Architecture Review Workspace */
        post: operations["createManualRecreation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an owned Workspace */
        get: operations["get_2"];
        put?: never;
        post?: never;
        /** Permanently delete an owned Workspace */
        delete: operations["delete"];
        options?: never;
        head?: never;
        /** Rename an owned Workspace */
        patch: operations["rename"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/reasoning/requirements/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a Requirement */
        delete: operations["deleteRequirement"];
        options?: never;
        head?: never;
        /** Update a Requirement */
        patch: operations["updateRequirement"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/reasoning/questions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an Unresolved Question */
        delete: operations["deleteQuestion"];
        options?: never;
        head?: never;
        /** Update an Unresolved Question */
        patch: operations["updateQuestion"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/reasoning/decisions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a Decision */
        delete: operations["deleteDecision"];
        options?: never;
        head?: never;
        /** Update a Decision */
        patch: operations["updateDecision"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/reasoning/assumptions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an Assumption */
        delete: operations["deleteAssumption"];
        options?: never;
        head?: never;
        /** Update an Assumption */
        patch: operations["updateAssumption"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/focus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Save Workspace focus and Canvas viewport */
        patch: operations["updateFocus"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/reasoning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workspace reasoning records */
        get: operations["get_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/portable-export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export portable content from an owned Workspace */
        get: operations["export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/architecture-revisions/{revisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an immutable Architecture Revision */
        get: operations["getRevision"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["currentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["currentEntitlements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/challenges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published Challenge catalog metadata */
        get: operations["catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/challenges/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the entitled published Challenge Version detail */
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ReviewBriefRequest: {
            systemDescription: string;
            reviewGoal: string;
        };
        ReviewBriefResponse: {
            /** Format: uuid */
            workspaceId?: string;
            systemDescription?: string;
            reviewGoal?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        JsonNode: {
            empty?: boolean;
            array?: boolean;
            null?: boolean;
            object?: boolean;
            float?: boolean;
            number?: boolean;
            missingNode?: boolean;
            integralNumber?: boolean;
            container?: boolean;
            /** @enum {string} */
            nodeType?: "ARRAY" | "BINARY" | "BOOLEAN" | "MISSING" | "NULL" | "NUMBER" | "OBJECT" | "POJO" | "STRING";
            valueNode?: boolean;
            bigDecimal?: boolean;
            bigInteger?: boolean;
            floatingPointNumber?: boolean;
            string?: boolean;
            double?: boolean;
            pojo?: boolean;
            short?: boolean;
            /** @deprecated */
            textual?: boolean;
            boolean?: boolean;
            int?: boolean;
            binary?: boolean;
            long?: boolean;
            embeddedValue?: boolean;
        };
        SaveArchitectureDocumentRequest: {
            /** Format: int64 */
            expectedVersion?: number;
            document: components["schemas"]["JsonNode"];
        };
        DocumentResponse: {
            /** Format: uuid */
            workspaceId?: string;
            /** Format: int64 */
            version?: number;
            document?: components["schemas"]["JsonNode"];
            /** Format: date-time */
            updatedAt?: string;
        };
        GrantConsentRequest: {
            policyVersion: string;
        };
        AiConsentResponse: {
            granted?: boolean;
            policyVersion?: string;
            /** Format: date-time */
            changedAt?: string;
            policy?: components["schemas"]["PolicyResponse"];
        };
        PolicyResponse: {
            currentVersion?: string;
            includedCategories?: string[];
            excludedCategories?: string[];
            providerRouting?: string;
            revocable?: boolean;
            priorTransmissionNotice?: string;
        };
        CreateWorkspaceRequest: {
            name: string;
            description: string;
            /** @enum {string} */
            type: "CHALLENGE" | "CUSTOM_DESIGN" | "ARCHITECTURE_REVIEW";
            /** @enum {string} */
            source: "CURATED_CHALLENGE" | "CUSTOM_DESIGN" | "IMPORT_PACKAGE" | "MANUAL_RECREATION";
        };
        CanvasViewport: {
            /** Format: double */
            x?: number;
            /** Format: double */
            y?: number;
            /** Format: double */
            zoom?: number;
        };
        WorkspaceSummary: {
            /** Format: uuid */
            id?: string;
            name?: string;
            description?: string;
            /** @enum {string} */
            type?: "CHALLENGE" | "CUSTOM_DESIGN" | "ARCHITECTURE_REVIEW";
            /** @enum {string} */
            source?: "CURATED_CHALLENGE" | "CUSTOM_DESIGN" | "IMPORT_PACKAGE" | "MANUAL_RECREATION";
            /** Format: uuid */
            challengeVersionId?: string;
            status?: string;
            /** Format: int32 */
            progressPercent?: number;
            saveState?: string;
            latestReviewState?: string;
            reviewBriefRequired?: boolean;
            focusStage?: string;
            focusPanel?: string;
            canvasViewport?: components["schemas"]["CanvasViewport"];
            clarifyPrompt?: string;
            suggestedNextAction?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        RequirementRequest: {
            kind: string;
            statement: string;
            priority: string;
            status: string;
            measurableTarget?: string;
            rationale?: string;
            source?: string;
            /** Format: int32 */
            orderIndex?: number;
        };
        RequirementResponse: {
            /** Format: uuid */
            id?: string;
            kind?: string;
            statement?: string;
            priority?: string;
            status?: string;
            measurableTarget?: string;
            rationale?: string;
            source?: string;
            /** Format: int32 */
            orderIndex?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        QuestionRequest: {
            question: string;
            whyItMatters: string;
            status: string;
            resolutionNotes?: string;
            relatedRequirementIds?: string[];
            relatedAssumptionIds?: string[];
            /** Format: uuid */
            resultingDecisionId?: string;
            /** Format: int32 */
            orderIndex?: number;
        };
        QuestionResponse: {
            /** Format: uuid */
            id?: string;
            question?: string;
            whyItMatters?: string;
            status?: string;
            resolutionNotes?: string;
            relatedRequirementIds?: string[];
            relatedAssumptionIds?: string[];
            /** Format: uuid */
            resultingDecisionId?: string;
            /** Format: int32 */
            orderIndex?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        DecisionRequest: {
            title: string;
            chosenOption: string;
            rationale: string;
            alternatives?: string;
            positiveConsequences?: string;
            risks?: string;
            status: string;
            evidenceRefs?: string[];
            /** Format: int32 */
            orderIndex?: number;
        };
        DecisionResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            chosenOption?: string;
            rationale?: string;
            alternatives?: string;
            positiveConsequences?: string;
            risks?: string;
            status?: string;
            evidenceRefs?: string[];
            /** Format: int32 */
            orderIndex?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AssumptionRequest: {
            category: string;
            quantitativeValue?: string;
            unit?: string;
            rationale?: string;
            confidence: string;
            status: string;
            source?: string;
            relatedRequirementIds?: string[];
            /** Format: int32 */
            orderIndex?: number;
        };
        AssumptionResponse: {
            /** Format: uuid */
            id?: string;
            category?: string;
            quantitativeValue?: string;
            unit?: string;
            rationale?: string;
            confidence?: string;
            status?: string;
            source?: string;
            relatedRequirementIds?: string[];
            /** Format: int32 */
            orderIndex?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        RevisionResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            workspaceId?: string;
            /** Format: int64 */
            documentVersion?: number;
            document?: components["schemas"]["JsonNode"];
            reasoningContext?: components["schemas"]["JsonNode"];
            /** Format: date-time */
            createdAt?: string;
        };
        CreateCustomDesignWorkspaceRequest: {
            name: string;
            systemIdea: string;
        };
        ImportPackageRequest: {
            name: string;
            systemDescription: string;
            reviewGoal: string;
            packageNode: components["schemas"]["JsonNode"];
        };
        ImportResponse: {
            packageNode?: components["schemas"]["JsonNode"];
            preview?: components["schemas"]["PortablePreview"];
        };
        PortablePreview: {
            title?: string;
            /** Format: int32 */
            requirements?: number;
            /** Format: int32 */
            assumptions?: number;
            /** Format: int32 */
            decisions?: number;
            /** Format: int32 */
            components?: number;
            /** Format: int32 */
            connections?: number;
            /** Format: int32 */
            bytes?: number;
        };
        PortalSession: {
            url?: string;
        };
        CheckoutSession: {
            id?: string;
            url?: string;
        };
        ManualRecreationRequest: {
            name: string;
            systemDescription: string;
            reviewGoal: string;
            knownRequirements?: string[];
            knownAssumptions?: string[];
        };
        RenameWorkspaceRequest: {
            name: string;
        };
        WorkspaceFocusRequest: {
            stage: string;
            panel: string;
            canvasViewport: components["schemas"]["JsonNode"];
        };
        ReasoningResponse: {
            requirements?: components["schemas"]["RequirementResponse"][];
            assumptions?: components["schemas"]["AssumptionResponse"][];
            questions?: components["schemas"]["QuestionResponse"][];
            decisions?: components["schemas"]["DecisionResponse"][];
            reviewBrief?: components["schemas"]["ReviewBriefResponse"];
        };
        CurrentUserResponse: {
            /** Format: uuid */
            id?: string;
            clerkSubject?: string;
        };
        Allowance: {
            /** Format: int64 */
            used?: number;
            /** Format: int32 */
            limit?: number | null;
        };
        BillingState: {
            status?: string;
            checkoutAvailable?: boolean;
            portalAvailable?: boolean;
            /** Format: date-time */
            paidThrough?: string;
        };
        CurrentEntitlements: {
            plan?: string;
            curatedChallengeAccess?: boolean;
            activeWorkspaces?: components["schemas"]["Allowance"];
            copilotTurns?: components["schemas"]["Allowance"];
            reviews?: components["schemas"]["Allowance"];
            /** Format: date-time */
            renewsAt?: string;
            billing?: components["schemas"]["BillingState"];
        };
        HealthResponse: {
            status?: string;
            service?: string;
            version?: string;
        };
        ChallengeSummary: {
            slug?: string;
            topic?: string;
            /** Format: uuid */
            versionId?: string;
            title?: string;
            description?: string;
            difficulty?: string;
            /** Format: int32 */
            estimatedMinutes?: number;
            skillFocus?: string;
        };
        ChallengeAttempt: {
            /** Format: uuid */
            id?: string;
            name?: string;
            status?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ChallengeDetail: {
            slug?: string;
            topic?: string;
            /** Format: uuid */
            versionId?: string;
            /** Format: int32 */
            version?: number;
            title?: string;
            description?: string;
            problemStatement?: string;
            difficulty?: string;
            /** Format: int32 */
            estimatedMinutes?: number;
            topicPacks?: string[];
            initialConstraints?: string[];
            skillCoverage?: components["schemas"]["SkillCoverage"][];
            scenarioPreview?: string[];
            attempts?: components["schemas"]["ChallengeAttempt"][];
        };
        SkillCoverage: {
            name?: string;
            level?: string;
            primary?: boolean;
            reviewDimension?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    saveReviewBrief: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewBriefRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReviewBriefResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentResponse"];
                };
            };
        };
    };
    save: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveArchitectureDocumentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DocumentResponse"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiConsentResponse"];
                };
            };
        };
    };
    grant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantConsentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiConsentResponse"];
                };
            };
        };
    };
    withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiConsentResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceSummary"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceSummary"];
                };
            };
        };
    };
    restore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceSummary"];
                };
            };
        };
    };
    createRequirement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequirementRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RequirementResponse"];
                };
            };
        };
    };
    createQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestionResponse"];
                };
            };
        };
    };
    createDecision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DecisionResponse"];
                };
            };
        };
    };
    createAssumption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssumptionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AssumptionResponse"];
                };
            };
        };
    };
    archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceSummary"];
                };
            };
        };
    };
    createRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RevisionResponse"];
                };
            };
        };
    };
    createCustomDesign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomDesignWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceSummary"];
                };
            };
        };
    };
    stripeWebhook: {
        parameters: {
            query?: never;
            header?: {
                "Stripe-Signature"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Stripe event accepted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    importPackage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportPackageRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceSummary"];
                };
            };
        };
    };
    validateImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JsonNode"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ImportResponse"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceSummary"];
                };
            };
        };
    };
    customerPortal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PortalSession"];
                };
            };
        };
    };
    checkout: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated idempotency key */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CheckoutSession"];
                };
            };
        };
    };
    completeCheckout: {
        parameters: {
            query: {
                session_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createManualRecreation: {
        parameters: {
            query?: never;
            header: {
                /** @description Caller-generated idempotency key */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualRecreationRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceSummary"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceSummary"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rename: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameWorkspaceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceSummary"];
                };
            };
        };
    };
    deleteRequirement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateRequirement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequirementRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RequirementResponse"];
                };
            };
        };
    };
    deleteQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuestionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestionResponse"];
                };
            };
        };
    };
    deleteDecision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateDecision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DecisionResponse"];
                };
            };
        };
    };
    deleteAssumption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAssumption: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssumptionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AssumptionResponse"];
                };
            };
        };
    };
    updateFocus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceFocusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceSummary"];
                };
            };
        };
    };
    get_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReasoningResponse"];
                };
            };
        };
    };
    export: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ImportResponse"];
                };
            };
        };
    };
    getRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                revisionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RevisionResponse"];
                };
            };
        };
    };
    currentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CurrentUserResponse"];
                };
            };
        };
    };
    currentEntitlements: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CurrentEntitlements"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    catalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChallengeSummary"][];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ChallengeDetail"];
                };
            };
        };
    };
}
