INSERT INTO challenges (id, slug, topic, status, created_at) VALUES
    ('44444444-4444-4444-8444-444444444444', 'notification-delivery', 'Async/eventing and reliability/operations', 'PUBLISHED', CURRENT_TIMESTAMP),
    ('55555555-5555-4555-8555-555555555555', 'distributed-job-processing', 'Async/eventing and data/read scaling', 'PUBLISHED', CURRENT_TIMESTAMP),
    ('66666666-6666-4666-8666-666666666666', 'global-rate-limiter', 'Request paths and global/multi-region systems', 'PUBLISHED', CURRENT_TIMESTAMP);

INSERT INTO challenge_versions (id, challenge_id, version, title, description, problem_statement, difficulty, estimated_minutes, topic_packs, initial_constraints, skill_coverage, scenario_preview, status, published_at) VALUES
('44444444-4444-4444-8444-444444444445', '44444444-4444-4444-8444-444444444444', 1, 'Design dependable notification delivery', 'Deliver time-sensitive notifications without losing intent or overwhelming downstream providers.', 'Design a notification delivery system for email, push, and SMS. Explain routing, retries, provider limits, user preferences, and how delivery state remains observable.', 'FOUNDATION', 30, '["request paths", "data/read scaling", "consistency/contention", "async/eventing", "reliability/operations", "global/multi-region systems"]', '["Notifications must survive worker restarts", "Providers impose per-channel quotas", "Users can change preferences while a message is queued"]', '[{"name":"async delivery","level":"introduce","primary":true,"reviewDimension":"async reasoning"},{"name":"rate limiting","level":"practice","primary":false,"reviewDimension":"scaling"},{"name":"failure recovery","level":"practice","primary":false,"reviewDimension":"reliability"}]', '["A provider returns intermittent 5xx responses", "A campaign creates a sudden burst", "A user disables a channel during delivery"]', 'PUBLISHED', CURRENT_TIMESTAMP),
('55555555-5555-4555-8555-555555555556', '55555555-5555-4555-8555-555555555555', 1, 'Design distributed job processing', 'Process long-running work reliably while keeping retries safe and progress visible.', 'Design a distributed job processing system. Explain admission, scheduling, leases, retries, idempotency, backpressure, and how operators recover stuck work.', 'FOUNDATION', 30, '["request paths", "data/read scaling", "consistency/contention", "async/eventing", "reliability/operations", "global/multi-region systems"]', '["Jobs may run for hours", "At-least-once delivery is expected", "Operators need durable progress and failure visibility"]', '[{"name":"job lifecycle","level":"introduce","primary":true,"reviewDimension":"requirements"},{"name":"idempotency","level":"practice","primary":false,"reviewDimension":"async reasoning"},{"name":"backpressure","level":"practice","primary":false,"reviewDimension":"scaling"}]', '["A worker disappears while holding a lease", "A retry storm exhausts capacity", "A job completes while its acknowledgement times out"]', 'PUBLISHED', CURRENT_TIMESTAMP),
('66666666-6666-4666-8666-666666666667', '66666666-6666-4666-8666-666666666666', 1, 'Design a global rate limiter', 'Protect a multi-region platform while keeping admission decisions predictable and available.', 'Design a global rate limiter for a multi-region API. Explain keying, storage, regional coordination, fail-open versus fail-closed behavior, and how limits remain understandable to clients.', 'FOUNDATION', 30, '["request paths", "data/read scaling", "consistency/contention", "async/eventing", "reliability/operations", "global/multi-region systems"]', '["Traffic arrives in multiple regions", "Limits must be enforced per customer and endpoint", "The limiter must add less than 5 ms at p99"]', '[{"name":"request admission","level":"introduce","primary":true,"reviewDimension":"requirements"},{"name":"distributed consistency","level":"practice","primary":false,"reviewDimension":"consistency"},{"name":"multi-region trade-offs","level":"practice","primary":false,"reviewDimension":"global systems"}]', '["A region loses connectivity to the coordination store", "A customer changes plan limits during a burst", "Clock skew causes boundary anomalies"]', 'PUBLISHED', CURRENT_TIMESTAMP);
